# Generated by Django 3.0.7 on 2020-06-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.SubjectCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.User'),
            preserve_default=False,
        ),
    ]
