# Generated by Django 3.0.7 on 2020-06-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='toggled',
            field=models.BooleanField(default=False),
        ),
    ]
