# Generated by Django 3.0.7 on 2020-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_award_toggled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_number_of_items',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
