# Generated by Django 3.0.7 on 2020-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20200625_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='api_key',
            field=models.CharField(default='111', max_length=100),
            preserve_default=False,
        ),
    ]
